import { Link, useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  CalendarDays,
  Target,
  Utensils,
  ShoppingCart,
} from "lucide-react";

import { useDietHistory } from "@/hooks/useDietHistory";

export default function HistoryDetailPage() {
  const { id } = useParams();

  const navigate = useNavigate();

  const { data = [], isLoading } = useDietHistory();

  const plan = data.find(
    (p) => p.id === Number(id)
  );

  if (isLoading) {
    return (
      <div className="flex h-72 items-center justify-center">
        <p className="text-slate-500">
          Loading diet plan...
        </p>
      </div>
    );
  }

  if (!plan) {
    return (
      <div className="mx-auto max-w-3xl py-20 text-center">
        <h2 className="text-3xl font-bold text-slate-900">
          Diet Plan Not Found
        </h2>

        <p className="mt-3 text-slate-500">
          This diet plan doesn't exist or has been deleted.
        </p>

        <Link
          to="/history"
          className="mt-8 inline-flex items-center rounded-xl bg-emerald-600 px-5 py-3 font-medium text-white transition hover:bg-emerald-700"
        >
          Back to History
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-6xl space-y-8">
      {/* Header */}

      <div className="flex items-start gap-4">
        <button
          onClick={() => navigate(-1)}
          className="rounded-xl border border-slate-200 bg-white p-3 transition hover:bg-slate-50"
        >
          <ArrowLeft size={20} />
        </button>

        <div className="flex-1">
          <h1 className="text-3xl font-bold text-slate-900">
            {plan.title}
          </h1>

          <div className="mt-3 flex flex-wrap gap-6 text-sm text-slate-600">
            <span className="flex items-center gap-2">
              <Target
                size={16}
                className="text-emerald-600"
              />
              {plan.goal}
            </span>

            <span className="flex items-center gap-2">
              <CalendarDays
                size={16}
                className="text-sky-600"
              />
              {new Date(
                plan.created_at
              ).toLocaleDateString()}
            </span>

            <span>
              Generated By: {plan.generated_by}
            </span>
          </div>
        </div>
      </div>

      {/* Meals */}

      <section className="space-y-6">
        <h2 className="text-2xl font-semibold text-slate-900">
          Meals
        </h2>

        {plan.meals.map((meal) => (
          <div
            key={meal.id}
            className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
          >
            <div className="mb-4 flex items-center gap-3">
              <div className="rounded-xl bg-emerald-100 p-2">
                <Utensils
                  size={18}
                  className="text-emerald-600"
                />
              </div>

              <div>
                <p className="text-sm text-slate-500">
                  {meal.meal_type}
                </p>

                <h3 className="text-xl font-semibold text-slate-900">
                  {meal.title}
                </h3>
              </div>
            </div>

            <div className="grid gap-4 rounded-xl bg-slate-50 p-4 md:grid-cols-4">
              <div>
                <p className="text-xs uppercase tracking-wide text-slate-500">
                  Calories
                </p>

                <p className="mt-1 text-lg font-semibold">
                  {meal.calories} kcal
                </p>
              </div>

              <div>
                <p className="text-xs uppercase tracking-wide text-slate-500">
                  Protein
                </p>

                <p className="mt-1 text-lg font-semibold">
                  {meal.protein} g
                </p>
              </div>

              <div>
                <p className="text-xs uppercase tracking-wide text-slate-500">
                  Carbohydrates
                </p>

                <p className="mt-1 text-lg font-semibold">
                  {meal.carbohydrates} g
                </p>
              </div>

              <div>
                <p className="text-xs uppercase tracking-wide text-slate-500">
                  Fat
                </p>

                <p className="mt-1 text-lg font-semibold">
                  {meal.fat} g
                </p>
              </div>
            </div>

            <div className="mt-6">
              <h4 className="mb-2 font-semibold text-slate-800">
                Recipe
              </h4>

              <p className="whitespace-pre-line leading-7 text-slate-600">
                {meal.recipe}
              </p>
            </div>
          </div>
        ))}
      </section>

      {/* Grocery List */}

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="mb-5 flex items-center gap-3">
          <ShoppingCart className="text-emerald-600" />

          <h2 className="text-2xl font-semibold">
            Grocery List
          </h2>
        </div>

        {plan.grocery_items.length === 0 ? (
          <p className="text-slate-500">
            No grocery items available.
          </p>
        ) : (
          <div className="grid gap-4 md:grid-cols-2">
            {plan.grocery_items.map((item) => (
              <div
                key={item.id}
                className="flex items-center justify-between rounded-xl border border-slate-200 p-4"
              >
                <span className="font-medium">
                  {item.item_name}
                </span>

                <span className="text-slate-500">
                  {item.quantity}
                </span>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}